--- 
title: "Practical Psychometrics: A Psychological Assessment Toolkit"
author: "W. Joel Schneider"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::tufte_html_book:
    toc: TRUE
    toc_depth: 1
    css: [toc.css,equity.css,mycss.css]
    tufte_features: []
    keep_md: true
    split_by: chapter
    highlight: pygments
    includes: 
      in_header: mj_config.html
documentclass: book
bibliography: [book.bib, packages.bib]
csl: apa.csl
link-citations: yes
github-repo: wjschne/toolkit
---

# Preface {-}

This book is not nearly complete. I hope someday to finish it.

<!-- <toggle-section open="false"> -->
<!-- <h5>Code</h5> -->

<!-- hello -->

<!-- </toggle-section> -->

```{r setup, include=FALSE}

source("loader.R")
knitr::write_bib(c(
  .packages(), 
  'bookdown', 
  'knitr', 
  'rmarkdown',
  'sn',
  'fMultivar',
  'IDPmisc',
  'tidyverse',
  'extrafont',
  'sn',
  'sjmisc',
  'psych',
  'tikzDevice',
  'gganimate',
  'ggforce',
  'qualvar',
  'patchwork',
  'simstandard',
  'modeest'), 'packages.bib')
```

```{r makesvg, eval=F}
c("SUDS",
  "DiscreteContinuous",
  "Stevens",
  "dichotomy",
  "Likert",
  "dice",
  "pdfIllustration",
  "pmf",
  "cdfDie",
  "QuantileFunction",
  "coin",
  "twocoin",
  "halfnormal") %>% walk(pdf2svg)
```



